### ISSUE TITLE
A call to SSPI failed, see inner exception. The message received was unexpected or badly formatted

### ISSUE THREAD

**Issue by mohammadhoseinGhezelsofla** [TalAloni/StandardSocketsHttpHandler#17]
Hello.
First of all, thank you very much for making this good library, it helps me a lot to improve the performance of my program.
I have a problem with all the services that exist in net framework to communicate with URLs, I was looking for a place to raise them.
There are some sites that have not provided the correct certificate, and when we try to get them through httpClient, WebClient or anything else, the program encounters an error, such as http://www.irmp3.ir  or http://www.resanejavan.com
I recently used your library to maybe fix this problem, but it still persists. I said to share the problem with you, so that maybe you could save me from this problem.
The code I have written so far is:
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Net.Http;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.IO;
using System.Threading;
using System.Net.Sockets;

namespace httpCertificateTesting
{
internal class Program
{
static void Main( string[] args )
{
try
{
ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls | SecurityProtocolType.Tls13 | SecurityProtocolType.SystemDefault;
ServicePointManager.ServerCertificateValidationCallback = (message, cert, chain, errors) => { Console.WriteLine($"message: {message}\ncert: {cert}\nchain: {chain}\nerrors: {errors}"); return true; };
ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
var handler = new StandardSocketsHttpHandler();
handler.ClientCertificateOptions = ClientCertificateOption.Manual;
handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { Console.WriteLine($"message: {message}\ncert: {cert}\nchain: {chain}\nerrors: {errors}"); return true; };
HttpClient client = new HttpClient( handler, false );
var r = client.GetStringAsync( "http://www.resanejavan.com/" ).Result;
Console.WriteLine( r.Length );
File.WriteAllText( "page.txt", r);
}
catch ( Exception ex )
{ Console.WriteLine( ex.ToString() ); }
Console.ReadLine();
}
}
}`

This code works well on Windows 10, but it has a problem on Windows Server 2012 r2 and gives the following error:
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStreamExtensions.<>c.<AuthenticateAsClientAsync>b__0_0(IAsyncResult iar) in StandardSocketsHttpHandler\Net\Security\Extensions\SslStreamExtensions.cs:line 18
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.ConnectHelper.<EstablishSslConnectionAsyncCore>d__5.MoveNext() in StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 183
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.<EstablishSslConnectionAsyncCore>d__5.MoveNext() in StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<CreateConnectionAsync>d__44.MoveNext() in StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<WaitForCreatedConnectionAsync>d__49.MoveNext() in StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 523
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__39.MoveNext() in StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 284
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext() in StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\RedirectHandler.cs:line 67
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at httpCertificateTesting.Program.Main(String[] args)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStreamExtensions.<>c.<AuthenticateAsClientAsync>b__0_0(IAsyncResult iar) in StandardSocketsHttpHandler\Net\Security\Extensions\SslStreamExtensions.cs:line 18
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.ConnectHelper.<EstablishSslConnectionAsyncCore>d__5.MoveNext() in StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 183
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.<EstablishSslConnectionAsyncCore>d__5.MoveNext() in StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<CreateConnectionAsync>d__44.MoveNext() in StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<WaitForCreatedConnectionAsync>d__49.MoveNext() in StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 523
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__39.MoveNext() in StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 284
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext() in StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\RedirectHandler.cs:line 67<---

I would be grateful if you could check the problem and help me to solve it

**Comment by TalAloni** [comment]
I'm not sure I understand the issue, and it's unlikely the issue is with StandardSocketsHttpHandler.

p.s. ServicePointManager is not directly used by SocketsHttpHandler AFAIK.
