### ISSUE TITLE
Getting an exception while using StandardSocketsHttpHandler with grpc.net on .net 4.7.2

### ISSUE THREAD

**Issue by yasoob** [TalAloni/StandardSocketsHttpHandler#21]
Hi! I was trying to use StandardSocketsHttpHandler with grpc.net on .net 4.7.2 however, it is throwing an exception:

```
System.AggregateException: One or more errors occurred. ---> Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The server returned an invalid or unrecognized response.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.") ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.<FillAsync>d__91.MoveNext() in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 1337
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection.<ReadNextResponseHeaderLineAsync>d__89.MoveNext() in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 1289
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection.<SendAsyncCore>d__61.MoveNext() in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 531
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.<SendAsyncCore>d__61.MoveNext() in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 725
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnectionPool.<SendWithNtConnectionAuthAsync>d__40.MoveNext() in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 316
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__39.MoveNext() in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 296
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext() in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\RedirectHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__74.MoveNext()
   --- End of inner exception stack trace ---
```

This is how I am using it:

```
StandardSocketsHttpHandler socketsHttpHandler = new StandardSocketsHttpHandler()
{
    SslOptions = new SslClientAuthenticationOptions
    {
        EncryptionPolicy = EncryptionPolicy.RequireEncryption,
        ClientCertificates = new X509CertificateCollection(),
        RemoteCertificateValidationCallback = (request, cert, chain, errors) =>
        {
            // Some server cert validation logic
            return true;
        },
    },
};

// Add client cert
socketsHttpHandler.SslOptions.ClientCertificates.Add(clientCert);

channel = GrpcChannel.ForAddress($"https://{options.DestinationIp}:{options.DestinationPort}", new GrpcChannelOptions { HttpHandler = socketsHttpHandler });
```

The same code works on .net 6 if I replace `StandardSocketsHttpHandler` with `SocketsHttpHandler`. Any ideas what might be causing this issue?

**Comment by TalAloni** [comment]
I'm not sure I'm following, gRPC requires HTTP/2,
StandardSocketsHttpHandler v2.2 does not support HTTP/2.

**Comment by yasoob** [comment]
Oh I see. This explains it then. I wasn't aware that StandardSocketsHttpHandler doesn't support HTTP/2. Is there any plan to add this support in the future? Thanks for your work on this package!

**Comment by TalAloni** [comment]
There is the experimental 3.0 version that supports unencrypted HTTP/2, there is no ALPN support in Framework 4.7.2 so encrypted HTTP/2 is not going to be easy.
