### ISSUE TITLE
Issue with DateTime Comparison for Lifetime Expiration

### ISSUE THREAD

**Issue by Horzo** [TalAloni/StandardSocketsHttpHandler#24]
https://github.com/TalAloni/StandardSocketsHttpHandler/blob/5cba41ed875925e02931bd9660bcad09d62f619d/StandardSocketsHttpHandler/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L556

The comparison (connection.CreationTime + lifetime <= DateTime.UtcNow) has a small chance of inaccuracies due to minor discrepancies between DateTime.UtcNow and DateTime values created in different parts of the system. Sometimes it throws:

`System.ArgumentOutOfRangeException)ex.InnerException:
The added or subtracted value results in an un-representable DateTime.
Parameter name: t
   at System.DateTime.op_Addition(DateTime d, TimeSpan t)
   at System.DateTimeOffset.op_Addition(DateTimeOffset dateTimeOffset, TimeSpan timeSpan)
   at System.Net.Http.HttpConnectionPool.ReturnConnection(HttpConnection connection) in HttpConnectionPool.cs`

Suggestion:
TimeSpan should be used for more accurate calculations, especially for high-frequency operations, by calculating elapsed time since CreationTime.

`TimeSpan elapsedLifetime = DateTime.UtcNow - connection.CreationTime;
bool lifetimeExpired = lifetime != Timeout.InfiniteTimeSpan && (lifetime == TimeSpan.Zero || elapsedLifetime >= lifetime);`

**Comment by TalAloni** [comment]
Thanks, this is a fork of Microsoft's SocketsHttpHandler,
If there is indeed an issue, I expect a fix was / would be applied in the official repo as well, can you please demonstrate this is indeed the case?

**Comment by TalAloni** [comment]
Closed for inactivity.
