### ISSUE TITLE
Object Reference Error while using in httpClient.SendAsync

### ISSUE THREAD

**Issue by Manjula-S** [TalAloni/StandardSocketsHttpHandler#5]
![image](https://user-images.githubusercontent.com/40023236/123205701-fe091f80-d4d7-11eb-8286-f50bf2fb2a87.png)

**Comment by TalAloni** [comment]
Please provide additional information

**Comment by TalAloni** [comment]
Which version of .NET Framework / .NET Core are you using?

**Comment by Manjula-S** [comment]
.Net framework 4.6.1

**Comment by Manjula-S** [comment]
at System.Net.Http.HttpRequestMessageExtensions.HasHeaders(HttpRequestMessage request)
   at System.Net.Http.StandardSocketsHttpHandler.ValidateAndNormalizeRequest(HttpRequestMessage request)
   at System.Net.Http.StandardSocketsHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request)
   at UL.IO.ECM.Extensions.HttpClientExtensions.PostAsJsonAsync(HttpClient httpClient, String uri, String value, Action`1 preAction) in C:\Users\825167\source\repos\Dev\ECM\Function\UL.IO.ECM.Functions\UL.IO.ECM.Functions\Extensions\HttpClientExtension.cs:line 50

**Comment by Manjula-S** [comment]
The same code works in another console application which is in same framework version. Looks strange the same code.

**Comment by TalAloni** [comment]
.NET Framework 4.6.1 is not supported. Use 4.7.2.

**Comment by TalAloni** [comment]
I've added a fallback to avoid this exception in .NET Framework 4.6.1, available in v2.2.0.3
